import {
  Wallet,
  CheckCircle,
  Coins,
  Shield,
  ArrowRightLeft,
  UserCheck,
  Package,
  Code,
  Image,
  Layers,
  Zap,
  BarChart3,
  FileDown,
} from "lucide-react";
import { BlockType } from "@/types";

export const blocks: BlockType[] = [
  {
    id: "connect_wallet",
    name: "Connect EVM Wallet",
    color: "from-purple-400 to-purple-600",
    icon: Wallet,
    description: "Connect your Web3 EVM wallet (MetaMask, Rabby) to Monad Testnet",
    category: "wallet",
    technology: "Monad",
    inputs: [
      {
        type: "select",
        label: "Wallet Type",
        options: ["MetaMask", "Rabby Wallet", "Browser Wallet Extension"],
        required: true,
        defaultValue: "Browser Wallet Extension",
      },
    ],
    compatibleWith: ["validate_wallet", "import_csv", "create_token", "deploy_contract", "deploy_nft"],
  },
  {
    id: "validate_wallet",
    name: "Validate Monad Wallet",
    color: "from-cyan-400 to-cyan-600",
    icon: CheckCircle,
    description: "Check EVM wallet address validity, MON balance, and token list",
    category: "validation",
    technology: "Monad",
    inputs: [
      {
        type: "select",
        label: "Validation Type",
        options: ["Quick Check", "Full Validation", "With Token Scan"],
        required: true,
        defaultValue: "Full Validation",
      },
      {
        type: "select",
        label: "Minimum Balance Check",
        options: ["Skip", "Check MON Only", "Check All Tokens"],
        required: false,
        defaultValue: "Check MON Only",
      },
    ],
    compatibleWith: ["import_csv", "validate_receiver", "transfer_token", "create_token", "deploy_contract", "deploy_nft"],
  },
  {
    id: "validate_receiver",
    name: "Validate EVM Receiver",
    color: "from-teal-400 to-teal-600",
    icon: UserCheck,
    description: "Validate receiver's 0x EVM wallet address before sending transactions",
    category: "validation",
    technology: "Monad",
    inputs: [
      {
        type: "address",
        label: "Receiver Address",
        placeholder: "0x... (EVM recipient address)",
        required: true,
      },
      {
        type: "select",
        label: "Validation Type",
        options: ["Format Only", "Format + Balance Check", "Full Validation"],
        required: true,
        defaultValue: "Format + Balance Check",
      },
    ],
    compatibleWith: ["transfer_token"],
  },
  {
    id: "transfer_token",
    name: "Transfer Token (MON)",
    color: "from-violet-400 to-violet-600",
    icon: ArrowRightLeft,
    description: "Transfer MON or standard ERC-20 tokens to a receiver address",
    category: "transfer",
    technology: "Monad",
    inputs: [
      {
        type: "select",
        label: "Token",
        options: ["MON", "USDT", "USDC", "WETH"],
        required: true,
        defaultValue: "MON",
      },
      {
        type: "address",
        label: "Receiver Address",
        placeholder: "0x... (EVM receiver address)",
        required: true,
      },
      {
        type: "number",
        label: "Amount",
        placeholder: "0.1",
        required: true,
      },
    ],
    compatibleWith: ["check_tx_status", "transaction_summary"],
  },
  {
    id: "batch_transfer",
    name: "Batch Transfer Engine",
    color: "from-amber-400 to-amber-600",
    icon: Zap,
    description: "Execute batch transfers of MON or ERC-20 tokens using MonadWorkflowExecutor.sol",
    category: "transfer",
    technology: "Monad",
    inputs: [
      {
        type: "select",
        label: "Token Type",
        options: ["MON", "ERC-20 Custom Token"],
        required: true,
        defaultValue: "MON",
      },
      {
        type: "select",
        label: "Execution Mode",
        options: ["Sequential (Viem)", "Atomic Multicall Contract"],
        required: true,
        defaultValue: "Atomic Multicall Contract",
      },
      {
        type: "select",
        label: "Batch Size",
        options: ["5", "10", "25", "50"],
        required: true,
        defaultValue: "10",
      },
    ],
    compatibleWith: ["check_tx_status", "transaction_summary"],
  },
  {
    id: "create_token",
    name: "Deploy ERC-20 Token",
    color: "from-emerald-400 to-emerald-600",
    icon: Coins,
    description: "Deploy a custom Solidity ERC-20 contract to Monad Testnet in 1 second",
    category: "deployment",
    technology: "Monad",
    inputs: [
      {
        type: "text",
        label: "Token Name",
        placeholder: "My Monad Token",
        required: true,
      },
      {
        type: "text",
        label: "Token Symbol",
        placeholder: "MMT",
        required: true,
      },
      {
        type: "number",
        label: "Initial Supply",
        placeholder: "1000000",
        required: true,
      },
      {
        type: "number",
        label: "Decimals",
        placeholder: "18",
        required: false,
        defaultValue: "18",
      },
    ],
    compatibleWith: ["check_tx_status", "validate_wallet"],
  },
  {
    id: "deploy_nft",
    name: "Deploy NFT Collection",
    color: "from-blue-400 to-blue-600",
    icon: Package,
    description: "Deploy a custom Solidity ERC-721 NFT contract to Monad Testnet",
    category: "deployment",
    technology: "Monad",
    inputs: [
      {
        type: "text",
        label: "NFT Name",
        placeholder: "Monad Sparks NFT",
        required: true,
      },
      {
        type: "text",
        label: "NFT Symbol",
        placeholder: "MSARK",
        required: true,
      },
      {
        type: "text",
        label: "Base URI",
        placeholder: "https://api.myproject.com/metadata/",
        required: true,
      },
    ],
    compatibleWith: ["mint_nft", "check_tx_status"],
  },
  {
    id: "mint_nft",
    name: "Mint Collection NFT",
    color: "from-pink-400 to-pink-600",
    icon: Image,
    description: "Mint a new NFT item from your deployed collection on Monad",
    category: "deployment",
    technology: "Monad",
    inputs: [
      {
        type: "address",
        label: "NFT Contract Address",
        placeholder: "0x... (EVM contract address)",
        required: true,
      },
      {
        type: "address",
        label: "Recipient Address",
        placeholder: "0x... (EVM recipient address)",
        required: true,
      },
      {
        type: "text",
        label: "Token URI",
        placeholder: "token-metadata.json",
        required: true,
      },
    ],
    compatibleWith: ["check_tx_status", "transaction_summary"],
  },
  {
    id: "deploy_contract",
    name: "AI Solidity Deployer",
    color: "from-indigo-400 to-indigo-600",
    icon: Code,
    description: "Compile and deploy raw Solidity code dynamically to Monad Testnet",
    category: "deployment",
    technology: "Solidity",
    inputs: [
      {
        type: "textarea",
        label: "Solidity Contract Code",
        placeholder: "pragma solidity ^0.8.20;\n\ncontract Custom {\n    // your code\n}",
        required: true,
      },
      {
        type: "text",
        label: "Contract Name",
        placeholder: "CustomContract",
        required: false,
      },
    ],
    compatibleWith: ["check_tx_status"],
  },
  {
    id: "check_tx_status",
    name: "Check Tx Status",
    color: "from-rose-400 to-rose-600",
    icon: Shield,
    description: "Verify that all transaction hashes in the workflow have been successfully mined",
    category: "monitoring",
    technology: "Monad",
    inputs: [],
    compatibleWith: ["transaction_summary"],
  },
  {
    id: "transaction_summary",
    name: "Transaction Summary",
    color: "from-slate-400 to-slate-600",
    icon: BarChart3,
    description: "Generate a summary report of executed transactions and gas fees paid in MON",
    category: "reporting",
    technology: "Monad",
    inputs: [],
    compatibleWith: ["export_report"],
  },
  {
    id: "export_report",
    name: "Export PDF/CSV Report",
    color: "from-stone-400 to-stone-600",
    icon: FileDown,
    description: "Download a report containing all workflow tx details and contract addresses",
    category: "reporting",
    technology: "Monad",
    inputs: [
      {
        type: "select",
        label: "Export Format",
        options: ["CSV", "JSON"],
        required: true,
        defaultValue: "CSV",
      },
      {
        type: "text",
        label: "Filename",
        placeholder: "parallelflow-execution-log",
        required: false,
        defaultValue: "parallelflow-execution-log",
      },
    ],
    compatibleWith: [],
  },
];

export const getAvailableTechnologies = () => {
  return Array.from(new Set(blocks.map((block) => block.technology)));
};

export const getBlocksByTechnology = (tech: string) => {
  return blocks.filter((block) => block.technology === tech);
};
